insert into usu_type (id, descrip) values (1,'Diretor'),(2,'Gerente'),(3,'Associado'),(4,'Supervisor'),(5,'Operador'),(6,'Contador');

insert into emp_type (id,descrip) values (1,"Conglomerado (economia)");
insert into emp_type (id,descrip) values (2,"Consórcio de empresas");
insert into emp_type (id,descrip) values (3,"Divisão (negócios)");
insert into emp_type (id,descrip) values (4,"Empresa de capital aberto");
insert into emp_type (id,descrip) values (5,"Empresa de capital fechado");
insert into emp_type (id,descrip) values (6,"Empresa de economia mista");
insert into emp_type (id,descrip) values (7,"Empresa estatal");
insert into emp_type (id,descrip) values (8,"Empresa familiar");
insert into emp_type (id,descrip) values (9,"Empresa de grande porte");
insert into emp_type (id,descrip) values (10,"Empresa privada");
insert into emp_type (id,descrip) values (11,"Empresa transnacional");
insert into emp_type (id,descrip) values (12,"Micro empreendedor individual");
insert into emp_type (id,descrip) values (13,"Microempresa");
insert into emp_type (id,descrip) values (14,"Empresa de mudanças");
insert into emp_type (id,descrip) values (15,"Sociedade anonima");
insert into emp_type (id,descrip) values (16,"Sociedade de propósito específico");
insert into emp_type (id,descrip) values (17,"Sociedade em comandita por ações");
insert into emp_type (id,descrip) values (18,"Sociedade em comandita simples");
insert into emp_type (id,descrip) values (19,"Sociedade em comum");
insert into emp_type (id,descrip) values (20,"Sociedade em conta de participação");
insert into emp_type (id,descrip) values (21,"Sociedade em nome coletivo");
insert into emp_type (id,descrip) values (22,"Sociedade empresária");
insert into emp_type (id,descrip) values (23,"Sociedade limitada");
insert into emp_type (id,descrip) values (24,"Sociedade por ações");
insert into emp_type (id,descrip) values (25,"Sociedade simples");
insert into emp_type (id,descrip) values (26,"Sociedade unipessoal por quotas");
insert into emp_type (id,descrip) values (27,"Subsidiária");
insert into emp_type (id,descrip) values (28,"Utilidade pública");
